sudo: required
services:
  - docker

before_install:
  - docker build -t chkbarlow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chkbarlow/react-test npm test

after_success:
  - docker build -t chkbarlow/multi-client ./client
  - docker build -t chkbarlow/multi-nginx ./nginx
  - docker build -t chkbarlow/multi-server ./server
  - docker build -t chkbarlow/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push chkbarlow/multi-client
  - docker push chkbarlow/multi-nginx
  - docker push chkbarlow/multi-server
  - docker push chkbarlow/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-787294604074"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY